travis:
  secure:
    BINSTAR_TOKEN: ogzuXRiAeKIz2KzFotFooUOAfYQLaaG7T30+RAFdHoTplLB947e0csVbDhgsGR7wPMTSo7RSoJclCQI2i5dFjRqQVJgzCoKzw187PVB1bseUmFdtiaSsX579jsk3kUp3yY4zRjUesxsWEEldysuP8LcjdPXL7zJ+DVAXOE1uCO1DXaKAL9fDPVirYcN8t/Br7PMObHkCIUKjRW2KwcuI6S1iI70m7ZDYWwbfZBhYEoBfOV2FnIv0LovtT9y3ecIdgTi5tHFTdRzSCIrNscW+HuyTKpyla+63uhDli6K6cIBIP+dWGgENPlHG0yccrTBbhWh9Ce6Zwi8K3hFCCpG4mIfiEX0E1456zg+Ymu8F4yeYvsbWjNSpYMX6l08V/OvygZ2gl3IDDnndjJbYoZ1QG3oKv0mvXnv8Lx3pd2mkfqjuPYCjmFdvD0aH2awGyC6X/oXpHB8NHVIgNCTqOUI3sf5qpbFJZYxIhNJetgW0x1rm6tZhd2Ip4DexywxB2PHv3shPKl23P03PoilF/ulUvjatxgmdxwWDGzppypN7Y/6jTtOaNO+0tFcOd9/+XEIe32yo0LiWCYslp7fPjjY7xdjbp/LZT2fkQ/d2HLy4rpTxhLIAaDREPIbvRGsT1VudtQQa5JwSzjsSYGp0f3hRJJzbLniCJZDMTc9Isey1PY4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
